from config.mistral_client import call_mistral


def reflection_agent(memory):
    """
    Reflection / Critic Agent:
    Reviews all agent outputs together and gives a final
    intelligent verdict — catching contradictions, warnings,
    and giving an overall travel recommendation.
    """

    budget_info = str(memory.get("budget", "Not available"))[:500]
    weather_info = str(memory.get("weather", "Not available"))[:500]
    hotel_info = str(memory.get("hotel", "Not available"))[:500]
    transport_info = str(memory.get("transport", "Not available"))[:500]
    destination_info = str(memory.get("destination", "Not available"))[:500]

    prompt = f"""
You are a senior AI travel consultant reviewing a complete travel plan.

Below is the full plan generated by multiple AI agents:

--- BUDGET ANALYSIS ---
{budget_info}

--- WEATHER REPORT ---
{weather_info}

--- DESTINATIONS ---
{destination_info}

--- HOTELS ---
{hotel_info}

--- TRANSPORT ---
{transport_info}

YOUR TASK:
1. Check if the budget is realistic given the hotel and transport costs
2. Check if the weather is safe for travel
3. Check for any contradictions between agents (e.g., budget says LOW but hotels are expensive)
4. Give an OVERALL VERDICT: Is this trip RECOMMENDED, PROCEED WITH CAUTION, or NOT RECOMMENDED?
5. Give 2-3 final practical tips for this specific trip

FORMAT YOUR RESPONSE AS:
OVERALL VERDICT: [RECOMMENDED / PROCEED WITH CAUTION / NOT RECOMMENDED]

Summary:
[2-3 sentences summarizing the plan quality]

Final Tips:
[2-3 practical tips]

Be honest, helpful, and concise. Plain text only.
"""

    try:
        result = call_mistral(prompt)
        if not result or "error" in result.lower():
            return "Reflection agent could not complete the review. Please verify your plan manually."
        return result
    except Exception as e:
        print(f"Reflection agent error: {e}")
        return "Reflection agent encountered an issue. Please review your plan manually."